[project]
name = "xml-tools"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "click==8.2.1",
    "defusedxml==0.7.1",
    "gitdb==4.0.12",
    "gitpython==3.1.44",
    "smmap==5.0.2",
]
