[versions]
revanced-patcher = "21.0.0"
# Tracking https://github.com/google/smali/issues/64.
#noinspection GradleDependency
smali = "3.0.5"
gson = "2.13.2"
agp = "8.2.2"
annotation = "1.9.1"
collections4 = "4.5.0"
desugar = "2.1.5"
nanohttpd = "2.3.1"
lang3 = "3.20.0"
okhttp3 = "4.12.0"
protobuf = "0.9.5"
protoc = "4.33.2"
preference = "1.2.1"
rxjava2 = "2.2.21"
rxjava2-android = "2.1.1"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "collections4" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "lang3" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protoc" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
rxjava2-android = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxjava2-android" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
